export const animationConfig = {
  hit: {
    durationMs: 120,
    flashDurationMs: 72,
    shakeDistancePixels: 5,
    shakeCycles: 3,
    scaleImpulse: 0.045,
    maximumFlashAlpha: 0.8,
    rotationReturnDurationMs: 90,
  },
  rewardBurst: {
    particleCount: 5,
    minimumSpeedPixelsPerSecond: 90,
    maximumSpeedPixelsPerSecond: 230,
    gravityPixelsPerSecondSquared: 430,
    durationMs: 520,
    labelRisePixelsPerSecond: 82,
    particleMinimumRadiusPixels: 4,
    particleMaximumRadiusPixels: 7,
    minimumAngleRadians: -Math.PI,
    maximumAngleRadians: 0,
    labelFontSizePixels: 24,
    labelStrokeWidthPixels: 4,
    labelColor: 0xffe183,
    labelStrokeColor: 0x3b210b,
    particleColors: [0xffc94a, 0xff8f32],
  },
  shatter: {
    columns: 2,
    rows: 2,
    durationMs: 610,
    minimumHorizontalSpeedPixelsPerSecond: 75,
    maximumHorizontalSpeedPixelsPerSecond: 210,
    minimumUpwardSpeedPixelsPerSecond: 120,
    maximumUpwardSpeedPixelsPerSecond: 290,
    gravityPixelsPerSecondSquared: 720,
    maximumRotationSpeedRadiansPerSecond: 4.8,
  },
  jackpotStun: {
    shakeDistancePixels: 7,
    shakeCycles: 5,
  },
  jackpotDisguise: {
    wobblePeriodMs: 420,
    wobbleAmplitudeRadians: 0.008,
  },
} as const
