export const animationConfig = {
  weaponHitEffect: {
    animationDurationMs: 180,
    displayScale: 0.5,
    spriteSheet: {
      assetLabel: 'effects/hit',
      sourceWidthPixels: 1_750,
      sourceHeightPixels: 218,
      frameWidthPixels: 350,
      frameHeightPixels: 218,
      frameCount: 5,
    },
  },
  hit: {
    durationMs: 120,
    flashDurationMs: 72,
    shakeDistancePixels: 5,
    shakeCycles: 3,
    scaleImpulse: 0.045,
    maximumFlashAlpha: 0.8,
    rotationReturnDurationMs: 90,
  },
  shatter: {
    columns: 2,
    rows: 2,
    durationMs: 610,
    minimumHorizontalSpeedPixelsPerSecond: 75,
    maximumHorizontalSpeedPixelsPerSecond: 210,
    minimumUpwardSpeedPixelsPerSecond: 120,
    maximumUpwardSpeedPixelsPerSecond: 290,
    gravityPixelsPerSecondSquared: 720,
    maximumRotationSpeedRadiansPerSecond: 4.8,
  },
  jackpotStun: {
    shakeDistancePixels: 7,
    shakeCycles: 5,
  },
  jackpotDisguise: {
    wobblePeriodMs: 420,
    wobbleAmplitudeRadians: 0.008,
  },
  equipmentReward: {
    burst: {
      minimumLaunchAngleRadians: -Math.PI * 0.72,
      maximumLaunchAngleRadians: -Math.PI * 0.28,
      minimumSpeedPixelsPerSecond: 300,
      maximumSpeedPixelsPerSecond: 500,
      spawnJitterPixels: 8,
      gravityPixelsPerSecondSquared: 1500,
      maximumRotationSpeedRadiansPerSecond: 2.6,
    },
    landing: {
      minimumOffsetPixels: 72,
      maximumOffsetPixels: 132,
      bottomSafeMarginPixels: 32,
      minimumBounceCount: 2,
      maximumBounceCount: 3,
      minimumVelocityRetention: 0.4,
      maximumVelocityRetention: 0.52,
      horizontalVelocityRetention: 0.72,
      minimumRestDurationMs: 120,
      maximumRestDurationMs: 190,
    },
    postCoinCollectionDelayMs: 140,
    noCoinFallbackDelayMs: 900,
    collectionDurationMs: 520,
    collectionArcHeightPixels: 68,
    failedDropDurationMs: 360,
    failedDropOffsetYPixels: -36,
    endingScale: 0.82,
  },
  settlementEquipmentSale: {
    groupRevealIntervalMs: 100,
    maximumGroupRevealDurationMs: 400,
    totalGoldRollDurationMs: 300,
  },
} as const
