export const coinRewardAnimationConfig = {
  spriteSheet: {
    sourceWidthPixels: 721,
    sourceHeightPixels: 103,
    frameWidthPixels: 103,
    frameHeightPixels: 103,
    frameCount: 7,
  },
  sprite: {
    minimumDisplaySizePixels: 27,
    maximumDisplaySizePixels: 35,
    flipFramesPerSecond: 18,
  },
  burst: {
    baseVisualCoinCount: 4,
    rewardPerAdditionalVisualCoin: 5,
    maximumVisualCoinCount: 18,
    maximumConcurrentVisualCoins: 72,
    minimumLaunchAngleRadians: -Math.PI * 0.82,
    maximumLaunchAngleRadians: -Math.PI * 0.18,
    minimumSpeedPixelsPerSecond: 220,
    maximumSpeedPixelsPerSecond: 390,
    spawnJitterPixels: 10,
    gravityPixelsPerSecondSquared: 820,
  },
  landing: {
    minimumOffsetPixels: 46,
    maximumOffsetPixels: 92,
    bottomSafeMarginPixels: 24,
    minimumBounceCount: 2,
    maximumBounceCount: 3,
    minimumVelocityRetention: 0.38,
    maximumVelocityRetention: 0.52,
    horizontalVelocityRetention: 0.76,
    minimumRestDurationMs: 120,
    maximumRestDurationMs: 190,
  },
  collection: {
    minimumDurationMs: 300,
    maximumDurationMs: 420,
    minimumArcHeightPixels: 34,
    maximumArcHeightPixels: 82,
    staggerPerCoinMs: 18,
    endingScale: 0.58,
    fadeStartProgress: 0.78,
  },
  counter: {
    digitRollDurationMs: 380,
    extraFullRotations: 1,
  },
} as const
